### ISSUE TITLE
how to use the SaveAtlas() and LoadAtlas() for relocalization?

### ISSUE THREAD

**Issue by nlwmode** [UZ-SLAMLab/ORB_SLAM3#128] opened 2020-09-22 08:32 UTC
I use the origin SaveAtlas() and LoadAtlas() for relocalization, and I also add the function in ShutDown()，and it execte worng!
It is a bit different to ORB_SLAM2  :< 
So how to use the atlas for relocalization?

**Comment by wpbird007** [comment] 2020-09-29 04:15
there is a  bug in  MapPoint::PreSave, detele KeyFrame when iter,you should fix it ,and then fix Tracking::Relocalization bug,and write a new function InitWithMap,and you can use the atlas map

**Comment by schizzz8** [comment] 2020-09-29 15:39
@wpbird007 I'm very interested in this issue.

Please, can you provide more details about the bugs you mention (e.g. source files, line numbers)???

Thanks

**Comment by thomCastillo** [comment] 2020-10-23 06:16
I'm also working on this topic. How did you solve this problem?

**Comment by colorDogs** [comment] 2020-10-26 08:29
@nlwmode can you provide more details about the bugs you mention (e.g. source files, line numbers)???

**Comment by thomCastillo** [comment] 2020-10-26 13:27
Hello @wpbird007 and @colorDogs 
I opened commented lines which about ATLAS in the code ([https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/System.cc#L99](url) and [https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/System.cc#L918](url)), but "The program has unexpectedly finished" on the [https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/MapPoint.cc#L591](url) line while saving Atlas. Therefore I commented this line and then I could saved Atlas successfully, but when I loaded the Atlas it tries to merge the maps but it gives the "The program has unexpectedly finished" error on the [https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/Sim3Solver.cc#L488](url) line this time. I tried room1 and corridor1 datasets like [https://www.youtube.com/watch?v=Rw_xP6lDizw](url). Why these lines are commented, is there a bug on the Atlas part of the code? But it seems to work the ORB SLAM3 videos on youtube. Do you know how to use Atlas and merge maps?

**Comment by colorDogs** [comment] 2020-10-26 13:38
> the

Now I only save the map successfully, if you read the map successfully, please contact me

**Comment by colorDogs** [comment] 2020-10-26 13:38
> Hello @wpbird007 and @colorDogs
> I opened commented lines which about ATLAS in the code ([https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/System.cc#L99](url) and [https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/System.cc#L918](url)), but "The program has unexpectedly finished" on the [https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/MapPoint.cc#L591](url) line while saving Atlas. Therefore I commented this line and then I could saved Atlas successfully, but when I loaded the Atlas it tries to merge the maps but it gives the "The program has unexpectedly finished" error on the [https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/Sim3Solver.cc#L488](url) line this time. I tried room1 and corridor1 datasets like [https://www.youtube.com/watch?v=Rw_xP6lDizw](url). Why these lines are commented, is there a bug on the Atlas part of the code? But it seems to work the ORB SLAM3 videos on youtube. Do you know how to use Atlas and merge maps?

Now I only save the map successfully, if you read the map successfully, please contact me

**Comment by thomCastillo** [comment] 2020-10-27 05:24
> > Hello @wpbird007 and @colorDogs
> > I opened commented lines which about ATLAS in the code ([https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/System.cc#L99](url) and [https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/System.cc#L918](url)), but "The program has unexpectedly finished" on the [https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/MapPoint.cc#L591](url) line while saving Atlas. Therefore I commented this line and then I could saved Atlas successfully, but when I loaded the Atlas it tries to merge the maps but it gives the "The program has unexpectedly finished" error on the [https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/Sim3Solver.cc#L488](url) line this time. I tried room1 and corridor1 datasets like [https://www.youtube.com/watch?v=Rw_xP6lDizw](url). Why these lines are commented, is there a bug on the Atlas part of the code? But it seems to work the ORB SLAM3 videos on youtube. Do you know how to use Atlas and merge maps?
> 
> Now I only save the map successfully, if you load the map successfully, please contact me

Hello, @colorDogs 
I added atlas file path at the and of the line https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/Examples/Monocular-Inertial/mono_inertial_tum_vi.cc#L118. When you add the last parameter the map is loading [ORB_SLAM3::System SLAM(argv[1],argv[2],ORB_SLAM3::System::IMU_MONOCULAR, true, 0, file_name, atlas_file_path);]. I can see the previous map which I saved on the screen, but while the maps are merging there is an error.

**Comment by colorDogs** [comment] 2020-10-27 06:03
> > > Hello @wpbird007 and @colorDogs
> > > I opened commented lines which about ATLAS in the code ([https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/System.cc#L99](url) and [https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/System.cc#L918](url)), but "The program has unexpectedly finished" on the [https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/MapPoint.cc#L591](url) line while saving Atlas. Therefore I commented this line and then I could saved Atlas successfully, but when I loaded the Atlas it tries to merge the maps but it gives the "The program has unexpectedly finished" error on the [https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/Sim3Solver.cc#L488](url) line this time. I tried room1 and corridor1 datasets like [https://www.youtube.com/watch?v=Rw_xP6lDizw](url). Why these lines are commented, is there a bug on the Atlas part of the code? But it seems to work the ORB SLAM3 videos on youtube. Do you know how to use Atlas and merge maps?
> > 
> > 
> > Now I only save the map successfully, if you load the map successfully, please contact me
> 
> Hello, @colorDogs
> I added atlas file path at the and of the line https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/Examples/Monocular-Inertial/mono_inertial_tum_vi.cc#L118. When you add the last parameter the map is loading [ORB_SLAM3::System SLAM(argv[1],argv[2],ORB_SLAM3::System::IMU_MONOCULAR, true, 0, file_name, atlas_file_path);]. I can see the previous map which I saved on the screen, but while the maps are merging there is an error.

Thank you very much for your reply
I'm ready to try
I'll let you know the results later.

**Comment by colorDogs** [comment] 2020-10-28 06:59
Hello, @wpbird007 
I finished saving and loading the map (but didn't see MapPoint on Pangolin), but a few seconds later a core dump will occur. My guess is that Altas's multi-map mechanism caused the problem. There was a problem with the map merge. I am debugging the cause of what happened. If you have any idea, please contact me

**Comment by colorDogs** [comment] 2020-11-03 07:14
@wpbird007  老哥加个联系方式呗? 还在做slam相关的事情吗?

**Comment by thomCastillo** [comment] 2020-11-03 10:43
@colorDogs I am still working on Atlas.My email adress thom.castillo@yandex.com.I changed some header files but there are some problems.If you contact me , we may discuss these problems.

**Comment by naoki-17** [comment] 2020-11-05 08:57
I have saved and loaded Atlas successfully and found that main problem occurred at the serialization of abstract GeometricCamera class, a self-defined class is a good idea to be serialized and then post-loaded to different camera module class. Also, there are some small problem in postload function to give a value for some pointers such as mpKFlowerID.

**Comment by colorDogs** [comment] 2020-11-05 09:16
> I have saved and loaded Atlas successfully and found that main problem occurred at the serialization of abstract GeometricCamera class, a self-defined class is a good idea to be serialized and then post-loaded to different camera module class. Also, there are some small problem in postload function to give a value for some pointers such as mpKFlowerID.

加个qq联系吧

**Comment by thomCastillo** [comment] 2020-11-05 12:23
@naoki-17 
I commented this line(https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/include/Atlas.h#L62) on Atlas header file and uncommented this line(https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/include/Atlas.h#L63). Thus I solved the geometric camera problem.
I added these on
ar & mPKFinitial;
ar & mpKFlowerID;
 (https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/include/Map.h#L68)

When I run the code it stopped on optimizar cc in this line.
https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/Optimizer.cc#L7202
It gives the errors below:
(https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/Thirdparty/g2o/g2o/core/sparse_optimizer.cpp#L83)
(https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/Thirdparty/g2o/g2o/core/sparse_optimizer.cpp#L253)

**Comment by naoki-17** [comment] 2020-11-06 13:09
> @naoki-17
> I commented this line(https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/include/Atlas.h#L62) on Atlas header file and uncommented this line(https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/include/Atlas.h#L63). Thus I solved the geometric camera problem.
> I added these on
> ar & mPKFinitial;
> ar & mpKFlowerID;
> (https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/include/Map.h#L68)
> 
> When I run the code it stopped on optimizar cc in this line.
> https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/src/Optimizer.cc#L7202
> It gives the errors below:
> (https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/Thirdparty/g2o/g2o/core/sparse_optimizer.cpp#L83)
> (https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/master/Thirdparty/g2o/g2o/core/sparse_optimizer.cpp#L253)

**Comment by naoki-17** [comment] 2020-11-06 13:29
@thomCastillo 
It stopped at LocalBundleAdjustment when I run monocular datasets，which seems the same problem.
https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/ef9784101fbd28506b52f233315541ef8ba7af57/src/LoopClosing.cc#L1722
 It failed at 
https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/ef9784101fbd28506b52f233315541ef8ba7af57/Thirdparty/g2o/g2o/core/block_solver.hpp#L75
Now I'm debugging. If any progress, shall we share here, thanks
More over, if LocalBundleAdjustment is umcommented, map merge will be finished perhaps with accuracy loss but the work can go on.

**Comment by 353264241** [comment] 2020-11-09 08:37
> @thomCastillo
> It stopped at LocalBundleAdjustment when I run monocular datasets，which seems the same problem.
> https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/ef9784101fbd28506b52f233315541ef8ba7af57/src/LoopClosing.cc#L1722
> 
> 
> It failed at
> https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/ef9784101fbd28506b52f233315541ef8ba7af57/Thirdparty/g2o/g2o/core/block_solver.hpp#L75
> 
> 
> Now I'm debugging. If any progress, shall we share here, thanks
> More over, if LocalBundleAdjustment is umcommented, map merge will be finished perhaps with accuracy loss but the work can go on.

Hello naoki-17 ,I come across the same segment fault in g2o block_solver.hppp L75. And I guess this is because we use the g2o in debug mode and the g2o provided by anthor has the error used in debug.

**Comment by richard-elvira** [comment] 2020-11-09 10:33
We are working in the Load/Save feature and solve the problem of relocalization in the Atlas. The Load/Save feature will be publish at the end of November, we hope to resolve the bug in relocalization in the same realease.

**Comment by 353264241** [comment] 2020-11-09 11:31
> We are working in the Load/Save feature and solve the problem of relocalization in the Atlas. The Load/Save feature will be publish at the end of November, we hope to resolve the bug in relocalization in the same realease.

Thanks for sharing this news, suggest using google protobuf to serialize the `KeyFrame` and `MapPoint`,which is a more convenient and debug-friendly serialization library on multi platforms.

**Comment by naoki-17** [comment] 2020-11-12 08:14
> > @thomCastillo
> > It stopped at LocalBundleAdjustment when I run monocular datasets，which seems the same problem.
> > https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/ef9784101fbd28506b52f233315541ef8ba7af57/src/LoopClosing.cc#L1722
> > 
> > It failed at
> > https://github.com/UZ-SLAMLab/ORB_SLAM3/blob/ef9784101fbd28506b52f233315541ef8ba7af57/Thirdparty/g2o/g2o/core/block_solver.hpp#L75
> > 
> > Now I'm debugging. If any progress, shall we share here, thanks
> > More over, if LocalBundleAdjustment is umcommented, map merge will be finished perhaps with accuracy loss but the work can go on.
> 
> Hello naoki-17 ,I come across the same segment fault in g2o block_solver.hppp L75. And I guess this is because we use the g2o in debug mode and the g2o provided by anthor has the error used in debug.

Hi，I got the same problem both in debug and release mode. Do you mean that it is a idea to use original g2o?

**Comment by honggesmile** [comment] 2020-11-27 08:56
> > I have saved and loaded Atlas successfully and found that main problem occurred at the serialization of abstract GeometricCamera class, a self-defined class is a good idea to be serialized and then post-loaded to different camera module class. Also, there are some small problem in postload function to give a value for some pointers such as mpKFlowerID.
> 
> 加个qq联系吧

老哥，你qq多少，能加个qq请教下吗

**Comment by honggesmile** [comment] 2020-11-30 07:24
> We are working in the Load/Save feature and solve the problem of relocalization in the Atlas. The Load/Save feature will be publish at the end of November, we hope to resolve the bug in relocalization in the same realease.
hi,richard-elvira .thanks for your works,that's so great!.  I also have tried to save and load map,  I have saved Atlas successfully，but when I load map ,the following error occurred：

```
Starting to read the save text file  file name:my_atlas.osa
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  input stream error
Aborted (core dumped)
```

I only comment    EraseObservation(pKFi) in MapPoint::PreSave(set<KeyFrame*>& spKF,set<MapPoint*>& spMP).

I cannot find any solutions,can you give me some advices.
Looking forward to your reply,thanks very much.

**Comment by honggesmile** [comment] 2020-12-11 10:49
> I have saved and loaded Atlas successfully and found that main problem occurred at the serialization of abstract GeometricCamera class, a self-defined class is a good idea to be serialized and then post-loaded to different camera module class. Also, there are some small problem in postload function to give a value for some pointers such as mpKFlowerID.

Hi，i 

> Hello, @wpbird007
> I finished saving and loading the map (but didn't see MapPoint on Pangolin), but a few seconds later a core dump will occur. My guess is that Altas's multi-map mechanism caused the problem. There was a problem with the map merge. I am debugging the cause of what happened. If you have any idea, please contact me

老哥，您好，我也是保存并且加载了地图，但是在Pangolin中看不到地图点(I finished saving and loading the map (but didn't see MapPoint on Pangolin),)，请问您解决了吗?

**Comment by franciscopower** [comment] 2021-04-08 19:24
Hi! I've been trying to solve it, but with no success either... Any news on this issue?

**Comment by neo-knight-td** [comment] 2021-04-20 12:20
@richard-elvira any news on that ?

**Comment by neo-knight-td** [comment] 2021-05-04 16:01
Hi all,

Just made the pull request with the Save/Load functionality : https://github.com/UZ-SLAMLab/ORB_SLAM3/pull/310

Hope it helps.

**Comment by Leonard-Yao** [comment] 2021-05-07 09:40
Hi, I try to execute the example  stereo_save and stereo_load from [](https://github.com/UZ-SLAMLab/ORB_SLAM3/tree/dcbb81929fae979384582e9c64c74a30e117cd86), and it worked well. However, I executed load program using the TUM-VI dataset , it crashed with the problem of "Segmentation          fault core dumped ". Whether or not it support the fisheye camera to save and load map? @richard-elvira

**Comment by neo-knight-td** [comment] 2021-05-07 10:14
@Leonard-Yao I did not test with inertial camera. Did you try uncommenting the  `ar & mvpBackupCamKan;` line in Atlas.h ?

**Comment by honggesmile** [comment] 2021-05-07 10:23
> @Leonard-Yao I did not test with fish-eye camera. Did you try uncommenting the `ar & mvpBackupCamKan;` line in Atlas.h ?

I tried to serialize the MvpbackupCamkan, but in IMU mode, the location was still wrong：
`1540 mLastFrame mVw :[]
1545 state:2
1548 state:2
1549 twb1:[2.5284798;
 0.55175859;
 2.6244438]
1550 Vwb1:[-0.18642974;
 0.0013929128;
 0.032918643]
1551 t12:0.04999995231628418
1552 Gz:[0;
 0;
 -9.8100004]
1553 Rwb1:[-0.040686633, 0.99660075, -0.071633935;
 0.33813688, 0.081196956, 0.93758726;
 0.94021684, 0.013925038, -0.3402915]
1554 mLastFrame.mImuBias:-0.026520704850554466
1557 state:2
1560 state:2
1567 state:2
addVertex: FATAL, a vertex with ID 391 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1569 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1570 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1571 has already been registered with this graph
addVertex: FATAL, a vertex with ID 392 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1572 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1573 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1574 has already been registered with this graph
addVertex: FATAL, a vertex with ID 393 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1575 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1576 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1577 has already been registered with this graph
addVertex: FATAL, a vertex with ID 394 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1578 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1579 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1580 has already been registered with this graph
addVertex: FATAL, a vertex with ID 395 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1581 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1582 has already been registered with this graph
addVertex: FATAL, a vertex with ID 1583 has already been registered with this graph
`

can you give me some advices, thanks

**Comment by neo-knight-td** [comment] 2021-05-07 10:29
@honggesmile did you try IMU with pinhole camera ? In EuRoC dataset for example ?

**Comment by Leonard-Yao** [comment] 2021-05-08 05:49
@neo-knight-td Thank you  for  your commentary. I uncommented the "ar & mvpBackupCamKan" and deleted "final" in line 36 from include/CameraModels/KannalaBrandt8.h. I'm not sure it's or not the best way to solve boost lib bug.Now the load program can achieve "*Merged detected". However, it also crashed with the problem of "Segmentation fault,  core dumped " from time to time.

**Comment by Leonard-Yao** [comment] 2021-05-08 05:58
@honggesmile IMU with  camera is not in my schedule at the moment. If  have any solution, I will let you know as soon as possible.

**Comment by franciscopower** [comment] 2021-05-14 18:01
Hi! I executed the save and load functions, but whenever the program ends in a situation where it lost tracking, it cannot save and crashes with the error `segmentation fault (core dumped)` , both in the mono_euroc and stereo_euroc datasets (I only tested with these two).

**Comment by neo-knight-td** [comment] 2021-05-15 06:42
@franciscopower, did you try the example scripts ? Is it that you try to save while tracking is lost or that you have had a tracking lost during the sequence ? On what sequence of the EuRoC dataset do you encounter the problem ?

**Comment by neo-knight-td** [comment] 2021-05-15 06:45
@Leonard-Yao did you also remark that you get a segmentation fault when you have a tracking lost on TUM dataset ?

**Comment by franciscopower** [comment] 2021-05-17 12:18
> @franciscopower, did you try the example scripts ? Is it that you try to save while tracking is lost or that you have had a tracking lost during the sequence ? On what sequence of the EuRoC dataset do you encounter the problem ? Did you try running ORB-SLAM 3 in Debug mode and launching it with gdb ?

I tested the example scripts on the MH01 Euroc dataset. At the end of the set, when the drone is landing, there is a moment when it looses tracking and, sometimes, cannot recover before saving, so it tries to save while tracking is lost. In those occasions I get the segmentation fault error. If I remove those frames from the dataset (cut the sequence short), it saves and loads properly. However, in the monocular mode, as soon as it detects a merge, it crashes with a segmentation fault error. 
I modified the stereo example to both load and save the atlas, and it saves correctly (provided it did't loose localization right before saving) and loads the saved map correctly. However, after loading the map and completing the sequence, it often fails to save again, crashing with the segmentation fault error.

**Comment by Jiaxin8122** [comment] 2021-08-21 14:30
> > I have saved and loaded Atlas successfully and found that main problem occurred at the serialization of abstract GeometricCamera class, a self-defined class is a good idea to be serialized and then post-loaded to different camera module class. Also, there are some small problem in postload function to give a value for some pointers such as mpKFlowerID.
> 
> 加个qq联系吧

Could

> @wpbird007 老哥加个联系方式呗? 还在做slam相关的事情吗?

Hello, 
Could you add me with qq or email?  812230984  Thx!
Regards

**Closed** 2021-12-23 10:18 UTC
